<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1ec29229-944d-4494-a558-d3dd82131155</testSuiteGuid>
   <testCaseLink>
      <guid>f6d1054a-09c3-4328-8f4f-20f6e6da2023</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day3/DataDrivenTesting</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8a5eb049-c18d-4739-a06d-91481fcb86ea</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataOne</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>8a5eb049-c18d-4739-a06d-91481fcb86ea</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>56ced83e-39b1-4a25-aae1-55a53499b0a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8a5eb049-c18d-4739-a06d-91481fcb86ea</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>3f9d9a3c-bf61-4c65-a1c0-521acb7f6096</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
